### ISSUE TITLE
大神，请教代码是如何更新editorTheme的page的？

### ISSUE THREAD

**Issue by ThreadDeath** [zhengguorong/h5maker#13]
查看单页的代码的时候，添加元素预览发现取的是editorTheme，但是看了很久也没看到更新editorTheme的pages的代码，基础可能不牢，望指教
![image](https://user-images.githubusercontent.com/5794404/46298041-b37d4180-c5d0-11e8-9142-f11f793db7ac.png)

**Comment by zhengguorong** [comment]
数据通过vuex管理，数据更改的地方在mutations定义
