### ISSUE TITLE
后台启动报错，是什么原因呢

### ISSUE THREAD

**Issue by sumWang** [zhengguorong/h5maker#2]

**Comment by zhengguorong** [comment]
你贴个错误信息给我看看

**Comment by sumWang** [comment]
$ npm run local

> h5maker@1.0.0 local F:\masker\h5maker-master
> NODE_ENV=localhost node ./bin/www

'NODE_ENV' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                          node_modules\\npm\\bin\\npm-cli.js" "run" "local"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! h5maker@1.0.0 local: `NODE_ENV=localhost node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the h5maker@1.0.0 local script 'NODE_ENV=localhost node ./bin                          /www'.

**Comment by wesdint** [comment]
应该是平台兼容问题，你用的是windows吧，package.json的scripts配置加个‘set’，改成： "local": "set NODE_ENV=localhost&&node ./bin/www"

**Comment by sumWang** [comment]
是的，加set可以启动了，赞
