### ISSUE TITLE
config 这个定义缺失

### ISSUE THREAD

**Issue by albertyou2** [zhengguorong/h5maker#5]
@ zhengguorong  你好
npm run local 还是起不来，原因是 config这个对象缺失，具体现象如下

$ npm run local

> h5maker@1.0.0 local /Users/youyin/Documents/h5maker
> NODE_ENV=localhost node ./bin/www

/Users/youyin/Documents/h5maker/auth/auth.service.js:22
    secret: config.secrets.session
                          ^

TypeError: Cannot read property 'session' of undefined

**Comment by zhengguorong** [comment]
没碰到过这个问题，你可以去auth.service.js，直接修改22行代码，直接给定一个字符串就好

**Comment by albertyou2** [comment]
好的，谢谢
